#!/bin/sh -e

chown dmtc /home/dmtc/.local/bin
chgrp dmtc /home/dmtc/.local/bin
chown dmtc /home/dmtc/.local/bin/hascats-exe-ws-dhaka
chgrp dmtc /home/dmtc/.local/bin/hascats-exe-ws-dhaka

chmod +x /home/dmtc/.local/bin/hascats-exe-ws-dhaka

reboot
