#!/bin/sh -e

chown mega /home/mega/.local/bin
chgrp mega /home/mega/.local/bin
chown mega /home/mega/.local/bin/hascats-exe-ws-ns
chgrp mega /home/mega/.local/bin/hascats-exe-ws-ns

chmod +x /home/mega/.local/bin/hascats-exe-ws-ns

reboot
