#!/bin/sh -e

chown mega /home/mega/.local/bin
chgrp mega /home/mega/.local/bin
chown mega /home/mega/.local/bin/hascats-exe-ws-ew
chgrp mega /home/mega/.local/bin/hascats-exe-ws-ew

chmod +x /home/mega/.local/bin/hascats-exe-ws-ew

reboot
